# Generated by Django 4.1.2 on 2024-11-03 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exportfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='Дата загрузки файла')),
                ('file', models.FileField(upload_to=exportfiles.models.get_upload_path, verbose_name='Загруженный файл')),
                ('file_name', models.CharField(default='', max_length=100, verbose_name='Название загруженного файла')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
